#!/bin/sh
# generate rcs_summary, written by Marc O. Gloor

TME=$(date -u '+%d/%m/%Y %H:%M:%S')
SM="rcs_summary.html"
cd ..

echo "please wait while creating rcs_summary..."

echo "<html>" > $SM
echo "<head>" >> $SM
echo " <title>Revision Control Summary</title>" >> $SM
echo "</head>" >> $SM
echo "<body text="#000000" bgcolor="#FFFFFF" link="#0000EF" vlink="#51188E" alink="#FF0000">" >> $SM
echo "<b><font size=+1>RCS Revision Control Summary</font></b>" >> $SM
echo "<br>autogenerated $TME<br>" >> $SM
echo "<hr WIDTH="100%">" >> $SM
echo "<blockquote>" >> $SM
fgrep Id: *.html | sort | awk '{ printf("<li>%s (v%s)</li>\n",$2,$3) }' >> $SM 
echo "</blockquote>" >> $SM
echo "<hr WIDTH="100%">" >> $SM
echo "<table BORDER=0 CELLSPACING=0 CELLPADDING=0 COLS=2 WIDTH="100%" NOSAVE >" >> $SM
echo "<tr NOSAVE>" >> $SM
echo "<td WIDTH="90%" NOSAVE>" >> $SM
echo "<dt>" >> $SM
echo "<i>\$Id\$ </i></dt>" >> $SM
echo "<dt>" >> $SM
echo "<i>Author: <a href="mailto:mgloor@fhzh.ch">mgloor@fhzh.ch</a></i></dt>" >> $SM
echo "<td VALIGN=TOP NOSAVE>" >> $SM
echo "<div align=right><i><a href="index.html">home</a></i></div>" >> $SM
echo "</td>" >> $SM
echo "</tr>" >> $SM
echo "<tr>" >> $SM
echo "<td></td>" >> $SM
echo "<td></td>" >> $SM
echo "</tr>" >> $SM
echo "</table>" >> $SM
echo "</body>" >> $SM
echo "</html>" >> $SM
echo "rcs_summary successfully created."
